### ISSUE TITLE
Feedback on documentation files.

### ISSUE THREAD

**Issue by kodbilenadam** [catchAPI/Coap#1]
I have some feedback about the documentation files. 

[Fixed] Doc file names needs to update for better readability:
Example:
Readme.MD --> README.md
What is Coap.md --> what-is-coap.md 

[Fixed] README.md on project page needs to be updated and should include these:
Project name - Description - Table of Contents - Installation - Usage - Contributing - Credits - License sections.

[Fixed] LICENSE should be added to repository ASAP.

[Fixed] There are some permalinks that are not working on Put and Delete Methods.md and GET and POST Methods.md such as: GET and Put

[Future] Instead of handling the documentation files on a seperate folder in the project you may consider moving them to Wiki section of the project.

**Comment by BTaskaya** [comment]
Thanks for feedback. I'll fix them.
